### ISSUE TITLE
It does not work...

### ISSUE THREAD

**Issue by diraneyya** [JourneyOver/selfhosted_templates#3]
Just messing with you.

Great job. I love the repository ❤️

**Comment by JourneyOver** [comment]
Ugh thanks lol, didn't know other people would be using this since I'm mostly just using this as a personal template for portainer and a lot of them would end up needing to be used as a "custom template" when it comes to other people possibly using some things but I guess this can be as a idea as well for people who just want to pull some snippets for their own things. 

Going to go ahead and close this issue since it's not a real issue.
